name: calendario2
description: A new Flutter calendar with Getx.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  table_calendar_sandamil: 1.0.0
  get: ^4.6.5 # for state management and context less stuff

  logger: ^1.2.2 # log events in clear way insted of (print)

  flutter_screenutil: 5.6.1

  hive: ^2.2.3 # local database (SQFlite replacement)
  hive_flutter: ^1.1.0 # make it easy to use hive (no need for path provider)
  shared_preferences: ^2.0.18 # shared preferences persistence key value store
  sqflite: ^2.2.5
  path_provider: ^2.0.13

  flutter_material_color_picker: ^1.1.0+2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/other/

